"""그래프 -> PyTorch 코드 (기획서 §7.2, §7.3, §10.4)."""

import ast

import pytest

from conftest import MINIVIT, ROOT
from torchflow import codegen
from torchflow.ir import load

RESNET = ROOT / "examples" / "resnet18.tfg.json"


def generated(path=MINIVIT) -> str:
    return codegen.generate(load(path), version="0.0.1")


def module_of(code: str, name: str):
    """생성된 소스를 실제로 실행해 클래스를 꺼낸다."""
    namespace: dict = {}
    exec(compile(code, "<generated>", "exec"), namespace)   # noqa: S102 - 생성 코드가 도는지가 요점
    return namespace[name]


def test_generated_code_parses_and_needs_only_torch():
    code = generated()

    ast.parse(code)
    assert "torchflow" not in code.replace("Generated by TorchFlow", "")
    imports = {line.split()[1] for line in code.splitlines()
               if line.startswith("import ") or line.startswith("from ")}
    assert imports <= {"__future__", "torch", "hashlib"}


def test_generation_is_deterministic():
    """같은 IR이면 바이트가 같다 - torchflow check의 전제다(§10.2)."""
    assert generated() == generated()


def test_composite_becomes_a_class_and_instance_an_attribute():
    code = generated()

    assert "class PatchEmbed(nn.Module):" in code
    assert "class MiniViT(nn.Module):" in code
    assert "self.proj = nn.Conv2d(in_channels=in_ch, out_channels=dim" in code
    # 컴포지트 doc은 클래스 docstring이 된다.
    assert '"""Conv patchifier followed by a flatten/transpose to token sequence."""' in code


def test_switch_branches_only_in_init():
    """forward는 변형을 모른다 - 런타임 isinstance 금지(§4.4.2 불변식)."""
    code = generated()
    block = code.split("class Block(nn.Module):")[1].split("class ")[0]
    init, forward = block.split("def forward")

    assert "if attn_type == 'baseline':" in init
    assert "SelfAttentionMHA" in init and "NoAttention" in init
    # forward에는 분기가 없고 호출 한 줄뿐이다.
    assert "self.attn(norm1)" in forward
    assert "if " not in forward


def test_repeat_becomes_a_sequential():
    assert ("self.blocks = nn.Sequential(*[Block(dim=dim, heads=heads, attn_type=attn_type) "
            "for _ in range(depth)])") in generated()


def test_expressions_become_python():
    """``$expr``는 파이썬의 부분집합이므로 네임스페이스만 벗기면 된다(§4.3)."""
    code = generated()
    assert "out_features=dim * mult" in code
    assert "num_classes: int" in code          # rt.num_classes -> 생성자 인자


def test_user_slots_round_trip():
    ir = load(MINIVIT)
    ir.graph.user_code = {"forward_tail": "print('hi')", "imports_helpers": "import math"}
    code = codegen.generate(ir)

    assert "# tf: user-begin forward_tail\n        print('hi')\n        # tf: user-end" in code
    assert "# tf: user-begin imports_helpers\nimport math\n# tf: user-end" in code


def test_generated_model_runs_and_matches_the_declared_output():
    torch = pytest.importorskip("torch")
    model = module_of(generated(), "MiniViT")(num_classes=10, seed=0)

    output = model(torch.randn(2, 3, 32, 32))
    assert tuple(output.shape) == (2, 10)


def test_generated_weights_are_bit_identical_to_the_kernel():
    """UI가 보여준 모델과 생성 코드가 같은 가중치에서 출발한다(§5.1.3, §10.4).

    이게 깨지면 "화면에서 본 grad"와 "스크립트가 내는 grad"가 다른 모델의 것이 된다.
    """
    torch = pytest.importorskip("torch")

    from torchflow.kernel.l1 import L1Pass, ProbeConfig

    ir = load(MINIVIT)
    model = module_of(codegen.generate(ir), "MiniViT")(num_classes=10, seed=0)
    generated_params = dict(model.named_parameters())

    pass_ = L1Pass(ir, rt={"num_classes": 10}, seed=0, probe=ProbeConfig(batch=2))
    pass_.probe_once()

    checked = 0
    for key, _node, _path in pass_.node_order:
        module_key = pass_.node_modules.get(key)
        module = pass_.session.modules.get(module_key) if module_key else None
        if module is None:
            continue
        prefix = pass_._label_path(key)
        for name, value in module.named_parameters():
            other = generated_params.get(f"{prefix}.{name}")
            assert other is not None, f"생성 코드에 없는 파라미터: {prefix}.{name}"
            assert torch.equal(other.detach(), value.detach()), f"{prefix}.{name} 값이 다르다"
            checked += 1
    assert checked > 50


def test_every_parameter_is_covered_by_seeded_init():
    """``_reset_parameters``만 있는 모듈(MHA)까지 포함해 빠짐이 없어야 한다(§5.1.3)."""
    pytest.importorskip("torch")
    code = generated()
    namespace: dict = {}
    exec(compile(code, "<generated>", "exec"), namespace)   # noqa: S102

    model = namespace["MiniViT"](num_classes=10, seed=0)
    assert namespace["init_coverage"](model) == []


def test_resnet_template_generates_and_runs():
    torch = pytest.importorskip("torch")
    code = generated(RESNET)
    model = module_of(code, "ResNet18")(num_classes=10, seed=0)

    assert tuple(model(torch.randn(2, 3, 32, 32)).shape) == (2, 10)


def test_shared_instance_is_built_once_and_called_twice():
    """가중치 공유는 코드에서도 공유로 남아야 한다(§7.2.5)."""
    ir = load(MINIVIT)
    scope = ir.composites["MLP"]
    # fc1을 두 번 부르는 그래프로 만든다.
    from torchflow.ir import Node

    scope.nodes.append(Node(label="fc1_again", id="dup", call="01J9I401", method="forward"))
    scope.edges = [edge for edge in scope.edges if edge != ["01J9Q4D3.output", "$out.y"]]
    scope.edges += [("01J9Q4D3.output", "dup.input"), ("dup.output", "$out.y")]

    body = codegen.generate(ir).split("class MLP(nn.Module):")[1].split("class ")[0]
    assert body.count("self.fc1 = nn.Linear") == 1
    assert body.count("self.fc1(") == 2


def test_graph_without_an_output_node_returns_its_sink():
    """Output 노드를 안 붙였어도 끝나는 데는 있다 - 아무도 소비하지 않는 값이 결과다."""
    ir = load(MINIVIT)
    ir.graph.nodes = [node for node in ir.graph.nodes if node.label != "logits"]
    ir.graph.edges = [edge for edge in ir.graph.edges if "01J9Q4B6" not in edge[1]]

    body = codegen.generate(ir).split("class MiniViT(nn.Module):")[1]
    assert "return head" in body


def test_train_block_stays_out_of_the_model():
    """학습 블록은 모델 코드에 나타나지 않는다. Output 뒤에 붙어 있어도 forward는 로짓을 돌려준다."""
    from torchflow.ir import ModuleGraph

    ir = ModuleGraph.model_validate({
        "graph": {"name": "tiny", "nodes": [
            {"id": "IN", "label": "x", "type": "torchflow.Input",
             "ports_out": [{"name": "x", "type": "Tensor", "shape": ["B", 8], "dtype": "float32"}]},
            {"id": "OUT", "label": "logits", "type": "torchflow.Output"},
            {"id": "TR", "label": "train", "type": "torchflow.Train",
             "args": {"optimizer": "sgd", "lr": 0.005, "steps": 7, "batch": 4}}],
            "edges": [["IN.x", "OUT.input"], ["OUT.output", "TR.input"]]}})
    code = codegen.generate(ir, version="0.0.1")
    ast.parse(code)
    assert "Train" not in code and "sgd" not in code
    assert "return x" in code
