"""그래프 -> PyTorch 코드 (기획서 §7.2, §7.3, 예시 §17.2).

`model-only` 단위: 파일 하나에 컴포지트 클래스와 최상위 모델, 그리고
``seeded_init``까지 인라인한다. **torch 말고는 아무것도 import하지 않는다** -
생성된 파일은 torchflow가 깔려 있지 않은 환경에서 그대로 돌아야 한다(§13.1 M6).

규칙 몇 개는 되돌리면 안 된다.

* 컴포지트 -> 클래스, 인스턴스 -> ``snake_case`` 속성, 호출 노드 1개 -> 문장 1개.
* **같은 인스턴스를 여러 노드가 부르면 ``__init__``에서 한 번 만들고 forward에서
  n번 부른다** - 가중치 공유(tied embedding)가 코드에서도 공유로 남는다.
* Switch는 ``__init__``의 ``if`` 분기만 만들고 **forward는 변형과 무관한 단일
  문장**이다(§4.4.2 불변식). 런타임 ``isinstance`` 분기 금지.
* 초기화는 ``seeded_init`` 한 곳에서 속성 경로 시드로 한다(§7.2.10). 생성자
  기본 초기화는 항상 덮어쓴다.

torch를 import하지 않는다 - hub 프로세스에서 그대로 돈다.
"""

from __future__ import annotations

import hashlib
import keyword
import re
from pathlib import Path
from typing import Any

from .ir import Composite, Graph, ModuleGraph, Node, canonical_json, split_endpoint, topo_order

# 함수형 노드 중 연산자로 쓰는 것들(§7.2.6). 나머지는 호출 그대로 남긴다.
OPERATORS = {"torch.add": "+", "torch.sub": "-", "torch.mul": "*", "torch.div": "/"}

SLOTS = ("imports_helpers", "class_attrs", "init_tail", "forward_tail")

HEADER = (
    "# Generated by TorchFlow {version} from {source} (ir_sha256={digest}).\n"
    '# Edits outside "tf: user-begin/end" slots are overwritten on the next graph change.\n'
    "# This file is part of your project and is your work.\n"
)


def ir_hash(ir: ModuleGraph) -> str:
    return hashlib.sha256(canonical_json(ir).encode()).hexdigest()


def generate(ir: ModuleGraph, *, version: str = "", source: str = "graph/model.tfg.json",
             specs: dict[str, Any] | None = None) -> str:
    """IR 하나를 ``model.py`` 한 파일로."""
    return _Writer(ir, version=version, source=source, specs=specs or {}).run()


def model_params(ir: ModuleGraph) -> dict[str, Any]:
    """생성된 최상위 클래스가 받는 인자들. 학습 워커가 무엇을 넘길지 여기서 안다."""
    return _Writer(ir, version="", source="", specs={})._top_params()


class CodegenError(ValueError):
    """코드로 옮길 수 없는 그래프. 노드에 귀속된다."""

    def __init__(self, node_id: str, message: str):
        super().__init__(message)
        self.node_id = node_id


class _Writer:
    def __init__(self, ir: ModuleGraph, *, version: str, source: str, specs: dict[str, Any]):
        self.ir = ir
        self.version = version
        self.source = source
        self.specs = specs
        self.used_composites: list[str] = []

    # 진입점
    def run(self) -> str:
        body = self._class(self.ir.graph, name=_class_name(self.ir.graph.name),
                           params=self._top_params(), top=True)
        # 컴포지트는 최상위보다 먼저 정의돼야 한다. 서로 참조하는 순서까지 따라간다.
        composites = [self._class(self.ir.composites[name], name=_class_name(name),
                                  params=_param_specs(self.ir.composites[name].params))
                      for name in self._composite_order()]
        parts = [
            HEADER.format(version=self.version or "0", source=self.source, digest=ir_hash(self.ir)),
            "from __future__ import annotations\n",
            "import torch\nfrom torch import Tensor, nn\n",
            self._slot("imports_helpers", indent=""),
            _seeded_init_source(),
            *composites,
            body,
        ]
        return "\n\n\n".join(part.strip("\n") for part in parts if part.strip()) + "\n"

    def _composite_order(self) -> list[str]:
        """참조 순서대로. 안쪽 컴포지트가 먼저 정의된다."""
        order: list[str] = []

        def visit(name: str) -> None:
            if name in order or name not in self.ir.composites:
                return
            composite = self.ir.composites[name]
            for instance in composite.instances.values():
                for referenced in _composites_of(instance):
                    visit(referenced)
            order.append(name)

        for instance in self.ir.graph.instances.values():
            for referenced in _composites_of(instance):
                visit(referenced)
        return order

    def _top_params(self) -> dict[str, Any]:
        """최상위 클래스의 ``__init__`` 인자: hparams + 쓰이는 rt 상수."""
        params: dict[str, Any] = {
            name: {"type": spec.type, "default": spec.default}
            for name, spec in self.ir.hparams.items()
        }
        for name in sorted(self._runtime_names()):
            params[name] = {"type": "int", "default": None}
        return params

    def _runtime_names(self) -> set[str]:
        """``rt.num_classes`` 처럼 그래프가 참조하는 런타임 상수들."""
        found: set[str] = set()
        for text in _all_expressions(self.ir):
            found.update(re.findall(r"\brt\.(\w+)", text))
        return found

    # 클래스 하나
    def _class(self, scope: Graph | Composite, *, name: str, params: dict[str, Any],
               top: bool = False) -> str:
        attrs, init_lines = self._instances(scope, params, top=top)
        forward = self._forward(scope, attrs, top=top)

        # 기본값이 있는 인자가 먼저, 없는 것(rt 상수)은 키워드 전용으로 뒤에 둔다.
        # 파이썬 문법상 기본값 뒤에 기본값 없는 인자를 그냥 놓을 수 없다.
        defaulted, required = [], []
        for param, spec in params.items():
            annotation = _annotation(spec.get("type"))
            default = spec.get("default")
            if default is None:
                required.append(f"{param}: {annotation}")
            else:
                defaulted.append(f"{param}: {annotation} = {default!r}")
        signature = ["self", *defaulted]
        if required or top:
            signature.append("*")
        signature.extend(required)
        if top:
            signature.append("seed: int = 0")

        doc = getattr(scope, "doc", None)
        lines = [f"class {name}(nn.Module):"]
        if doc:
            lines.append(f'    """{doc}"""')
            lines.append("")
        lines.append(f"    def __init__({', '.join(signature)}) -> None:")
        lines.append("        super().__init__()")
        lines.extend(f"        {line}" for line in init_lines)
        if top:
            # 모든 파라미터는 여기 한 곳에서 경로 시드로 초기화된다(§7.2.10).
            lines.append("        seeded_init(self, seed)")
        lines.append(self._slot("init_tail", indent="        "))
        lines.append("")
        lines.extend(forward)
        return "\n".join(line for line in lines if line is not None)

    def _instances(self, scope, params: dict[str, Any],
                   *, top: bool) -> tuple[dict[str, str], list[str]]:
        """인스턴스 -> 속성. 여러 호출 노드가 같은 인스턴스를 가리키면 속성도 하나다."""
        attrs: dict[str, str] = {}
        lines: list[str] = []
        taken: set[str] = set()

        for instance_id, instance in scope.instances.items():
            label = next((node.label for node in scope.nodes if node.call == instance_id),
                         instance.label)
            attr = _unique(_snake(label), taken)
            attrs[instance_id] = attr
            lines.extend(self._construct(attr, instance, scope, top=top))
        return attrs, lines

    def _construct(self, attr: str, instance, scope, *, top: bool) -> list[str]:
        kind = instance.type

        if kind == "torchflow.Switch":
            return self._switch(attr, instance)
        if kind == "torchflow.Repeat":
            return self._repeat(attr, instance)
        if kind.startswith("cell:"):
            raise CodegenError(attr, f"code cells are not generated yet ({kind})")

        target = _call_target(kind)
        args = _args(instance.args)
        return [f"self.{attr} = {target}({args})"]

    def _switch(self, attr: str, instance) -> list[str]:
        """변형 분기는 ``__init__``에만. forward는 변형을 모른다(§4.4.2)."""
        active = _expression(instance.active)
        lines: list[str] = []
        for index, (variant_name, variant) in enumerate((instance.variants or {}).items()):
            branch = "if" if index == 0 else "elif"
            target = _call_target(variant["type"])
            annotation = ": nn.Module" if index == 0 else ""
            lines.append(f"{branch} {active} == {variant_name!r}:")
            lines.append(f"    self.{attr}{annotation} = {target}({_args(variant.get('args', {}))})")
        lines.append("else:")
        lines.append(f"    raise ValueError(f'unknown variant: {{{active}!r}}')")
        return lines

    def _repeat(self, attr: str, instance) -> list[str]:
        body = _call_target(instance.body or "")
        count = _expression(instance.count)
        bound = _args(instance.bind or {})
        mode = instance.mode or "sequential"

        if mode == "shared_weights":
            # 인스턴스 하나를 n번 부른다. forward의 루프가 그것을 드러낸다.
            return [f"self.{attr} = {body}({bound})", f"self.{attr}_times = {count}"]
        if mode == "sequential":
            return [f"self.{attr} = nn.Sequential(*[{body}({bound}) for _ in range({count})])"]
        return [f"self.{attr} = nn.ModuleList([{body}({bound}) for _ in range({count})])"]

    # forward
    def _forward(self, scope, attrs: dict[str, str], *, top: bool) -> list[str]:
        inputs, statements, outputs = [], [], []
        values: dict[str, str] = {}
        taken: set[str] = set()

        if isinstance(scope, Composite):
            for port in scope.ports.get("in", []):
                name = _unique(_snake(port.name), taken)
                values[f"$in.{port.name}"] = name
                inputs.append(f"{name}: Tensor")

        for node in topo_order(list(scope.nodes), list(scope.edges)):
            if node.type == "torchflow.Input":
                for port in node.ports_out or []:
                    name = _unique(_snake(port.name), taken)
                    values[f"{node.id}.{port.name}"] = name
                    inputs.append(f"{name}: Tensor")
                continue

            incoming = _incoming(scope, node.id, values)
            if node.type == "torchflow.Output":
                outputs = list(incoming.values())
                continue

            statement, produced = self._statement(node, scope, attrs, incoming, taken)
            comment = self._shape_comment(node)
            statements.append(f"{statement}{comment}")
            for port, variable in produced.items():
                values[f"{node.id}.{port}"] = variable

        if isinstance(scope, Composite):
            outputs = [values[src] for src, dst in scope.edges
                       if split_endpoint(dst)[0] == "$out" and src in values]
        elif not outputs:
            # Output 노드를 안 붙였어도 끝나는 데는 있다 - 아무도 소비하지 않는 값이 결과다.
            consumed = {src for src, _ in scope.edges}
            outputs = [variable for key, variable in values.items() if key not in consumed]

        lines = [f"    def forward({', '.join(['self', *inputs])}) -> Tensor:"]
        lines.extend(f"        {line}" for line in statements)
        lines.append(self._slot("forward_tail", indent="        "))
        if outputs:
            lines.append(f"        return {', '.join(outputs)}")
        else:
            lines.append("        return None  # 그래프에 출력이 연결되지 않았습니다")
        return lines

    def _statement(self, node: Node, scope, attrs: dict[str, str], incoming: dict[str, str],
                   taken: set[str]) -> tuple[str, dict[str, str]]:
        name = _unique(_snake(node.label), taken)
        ports = [port.name for port in (node.ports_out or [])] or ["output"]
        produced = {port: (name if len(ports) == 1 else f"{name}_{port}") for port in ports}
        target = ", ".join(produced.values())

        if node.call:
            attr = attrs.get(node.call)
            if attr is None:
                raise CodegenError(node.id, f"unknown instance {node.call}")
            instance = scope.instances[node.call]
            if (instance.mode or "") == "shared_weights":
                # 공유 가중치 Repeat: 루프가 코드에 그대로 보인다.
                stream = next(iter(incoming.values()), "None")
                return (f"{target} = {stream}\n        "
                        f"for _ in range(self.{attr}_times):\n            "
                        f"{target} = self.{attr}({target})", produced)
            call = f"self.{attr}" + (f".{node.method}" if node.method not in (None, "forward") else "")
            return f"{target} = {call}({_call_args(incoming, node.args)})", produced

        kind = (node.type or "").split("@")[0]
        if kind in OPERATORS and len(incoming) == 2:
            left, right = incoming.values()
            return f"{target} = {left} {OPERATORS[kind]} {right}", produced
        return f"{target} = {kind}({_call_args(incoming, node.args)})", produced

    def _shape_comment(self, node: Node) -> str:
        """문장 끝 shape 주석(§7.2.4). L0를 돌린 적이 있을 때만 붙는다."""
        spec = (self.specs.get(node.id) or {}).get("spec") or {}
        shape = spec.get("shape")
        return f"  # ({', '.join(str(dim) for dim in shape)})" if shape else ""

    def _slot(self, slot: str, *, indent: str) -> str:
        """user-slot 보호 구역(§7.6.1). 안쪽 바이트는 IR이 들고 있다가 그대로 되돌려준다."""
        saved = (self.ir.graph.user_code or {}).get(slot, "")
        lines = [f"{indent}# tf: user-begin {slot}"]
        if saved:
            lines.extend(f"{indent}{line}" if line.strip() else "" for line in saved.splitlines())
        lines.append(f"{indent}# tf: user-end")
        return "\n".join(lines)


# 표현식과 이름


def _incoming(scope, node_id: str, values: dict[str, str]) -> dict[str, str]:
    """이 노드의 입력 포트 -> 변수 이름."""
    found: dict[str, str] = {}
    for src, dst in scope.edges:
        target, port = split_endpoint(dst)
        if target == node_id and src in values:
            found[port] = values[src]
    return found


def _call_args(incoming: dict[str, str], args: dict[str, Any]) -> str:
    """입력이 하나면 위치 인자로 - ``self.norm1(x)``가 ``self.norm1(input=x)``보다 읽힌다."""
    parts = list(incoming.values()) if len(incoming) == 1 else [
        f"{port}={variable}" for port, variable in incoming.items()]
    parts.extend(f"{key}={_expression(value)}" for key, value in args.items())
    return ", ".join(parts)


def _args(args: dict[str, Any]) -> str:
    return ", ".join(f"{key}={_expression(value)}" for key, value in args.items())


def _expression(value: Any) -> str:
    """IR 값 -> 파이썬 식. ``$hp``/``$p``/``$expr`` 참조는 인자 이름으로 풀린다."""
    from .ir import ref_of

    ref = ref_of(value)
    if ref is not None:
        kind, inner = ref
        if kind == "$expr":
            # 표현식 문법은 파이썬의 부분집합이다(§4.3). 네임스페이스만 벗긴다.
            return re.sub(r"\b(?:hp|p|rt)\.(\w+)", r"\1", str(inner))
        return _snake(str(inner))
    if isinstance(value, dict):
        return "{" + ", ".join(f"{k!r}: {_expression(v)}" for k, v in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_expression(item) for item in value) + "]"
    return repr(value)


def _call_target(kind: str) -> str:
    """``composite:MLP`` -> ``MLP``, ``torch.nn.Linear@2.11`` -> ``nn.Linear``."""
    name = kind.split("@")[0]
    if name.startswith("composite:"):
        return _class_name(name.split(":", 1)[1])
    return name.replace("torch.nn.", "nn.", 1) if name.startswith("torch.nn.") else name


def _composites_of(instance) -> set[str]:
    found = set()
    for candidate in [instance.type, instance.body,
                      *[variant.get("type") for variant in (instance.variants or {}).values()]]:
        if isinstance(candidate, str) and candidate.startswith("composite:"):
            found.add(candidate.split(":", 1)[1])
    return found


def _all_expressions(ir: ModuleGraph) -> list[str]:
    """``$expr`` 문자열 전부. rt 참조를 찾는 데 쓴다."""
    from .ir import iter_refs

    found: list[str] = []

    def collect(source) -> None:
        for kind, inner in iter_refs(getattr(source, "args", {}) or {}):
            if kind == "$expr":
                found.append(str(inner))
        for field in ("active", "count"):
            value = getattr(source, field, None)
            for kind, inner in iter_refs({"_": value} if value is not None else {}):
                if kind == "$expr":
                    found.append(str(inner))
        for variant in (getattr(source, "variants", None) or {}).values():
            for kind, inner in iter_refs(variant.get("args", {})):
                if kind == "$expr":
                    found.append(str(inner))
        for key, value in (getattr(source, "bind", None) or {}).items():
            for kind, inner in iter_refs({key: value}):
                if kind == "$expr":
                    found.append(str(inner))

    for scope in [ir.graph, *ir.composites.values()]:
        for node in scope.nodes:
            collect(node)
        for instance in scope.instances.values():
            collect(instance)
    return found


def _param_specs(params) -> dict[str, Any]:
    """``HParam`` 모델 -> ``{type, default}`` dict. 컴포지트 파라미터도 같은 모양이다."""
    return {name: {"type": spec.type, "default": spec.default} for name, spec in params.items()}


def _annotation(kind: str | None) -> str:
    return {"int": "int", "float": "float", "bool": "bool", "str": "str",
            "enum": "str"}.get(kind or "", "int")


def _class_name(name: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z]+", " ", name).strip()
    if not cleaned:
        return "Model"
    if " " not in cleaned and cleaned[:1].isupper():
        return cleaned          # 이미 PascalCase면 그대로 둔다(MiniViT -> MiniViT)
    return "".join(word[:1].upper() + word[1:] for word in cleaned.split())


# 지역 변수가 가리면 곤란한 내장 이름들. 뒤에 밑줄을 붙인다.
SHADOWED = {"id", "input", "type", "sum", "max", "min", "next", "object", "slice",
            "filter", "format", "hash", "vars", "list", "dict", "set", "map", "all", "any"}


def _snake(label: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "_", label).strip("_")
    cleaned = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", cleaned).lower() or "node"
    if cleaned[0].isdigit():
        cleaned = f"n{cleaned}"
    return f"{cleaned}_" if keyword.iskeyword(cleaned) or cleaned in SHADOWED else cleaned


def _unique(name: str, taken: set[str]) -> str:
    candidate = name
    index = 2
    while candidate in taken:
        candidate = f"{name}{index}"
        index += 1
    taken.add(candidate)
    return candidate


def _seeded_init_source() -> str:
    """``runtime/init.py``를 그대로 인라인한다.

    L1 커널이 import하는 것과 **같은 바이트**여야 UI와 생성 코드가 같은
    가중치에서 출발한다(§5.1.3, §10.4의 step-0 state_dict 동일성 CI).
    """
    source = (Path(__file__).parent / "runtime" / "init.py").read_text(encoding="utf-8")
    body = source.split('"""', 2)[-1]           # 모듈 docstring만 떼고 함수 본문은 그대로
    for line in ("from __future__ import annotations", "import torch",
                 "from torch import nn", "import hashlib"):
        body = body.replace(line + "\n", "")
    return "import hashlib\n\n\n" + body.strip()
