"""그래프 -> 돌릴 수 있는 프로젝트 폴더 (기획서 §7.3 ``package`` 단위, 예시 §17.2).

``model-only``가 파일 하나라면 이쪽은 **프로젝트**다. 나오는 것:

    <out>/pyproject.toml
    <out>/reproduce.sh
    <out>/env.lock.json
    <out>/conf/config.json          (백엔드가 hydra면 config.yaml)
    <out>/conf/overrides/           (학습 중 바꾼 값이 여기 떨어진다, §5.7.2)
    <out>/src/<proj>/{__init__,model,utils,data,train}.py

규칙 하나가 전부를 규정한다: **나온 코드는 torchflow 없이 돈다**(§13.1 M6 게이트).
그래서 데이터 적재도 학습 루프도 여기서 다시 쓴다 - 워커(``torchflow/worker``)와
같은 규칙을 같은 순서로 따르되, import는 torch와 표준 라이브러리뿐이다.
``torchflow check``가 그 무의존과 바이트 일치를 CI에서 강제한다(§10.2).

torch를 import하지 않는다 - hub 프로세스에서 그대로 돈다.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from . import codegen
from .ir import ModuleGraph

BACKENDS = ("argparse-dataclass", "hydra")

# train.py의 Config 기본값. Train 블록이 있으면 그 값이 이긴다(hub의 /api/train과 같은 규칙).
BASE_CONFIG: list[tuple[str, Any]] = [
    ("seed", 0),
    ("deterministic", False),
    ("device", "auto"),
    ("data_root", "data"),
    ("dataset", "teacher"),
    ("batch", 32),
    ("steps", 500),
    ("optimizer", "adamw"),
    ("lr", 1e-3),
    ("weight_decay", 0.0),
    ("scheduler", "none"),
    ("warmup_steps", 0),
    ("grad_clip", 0.0),
    ("log_every", 5),
    ("eval_every", 100),
    ("run_dir", "runs/local"),
    ("overrides", ""),
    ("resume", ""),
]

TRAIN_ARGS = ("optimizer", "lr", "weight_decay", "steps", "batch", "scheduler", "warmup_steps")


def build(ir: ModuleGraph, out: Path | str, *, version: str = "",
          source: str = "graph/model.tfg.json", backend: str = "argparse-dataclass",
          specs: dict[str, Any] | None = None, graph_path: Path | str | None = None) -> list[Path]:
    """프로젝트를 통째로 쓴다. 돌려주는 것은 쓴 파일 목록(정렬됨)."""
    if backend not in BACKENDS:
        raise ValueError(f"unknown config backend {backend!r} (have {', '.join(BACKENDS)})")
    out = Path(out)
    proj = module_name(ir)
    config = config_defaults(ir)
    model_args = model_arguments(ir, config)
    written: list[Path] = []

    def write(relative: str, text: str) -> None:
        path = out / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)

    head = _header(version)
    write(f"src/{proj}/__init__.py", head + f'"""Generated by TorchFlow. {proj} model package."""\n')
    write(f"src/{proj}/model.py",
          codegen.generate(ir, version=version, source=source, specs=specs, shared_utils=True))
    write(f"src/{proj}/utils.py", head + UTILS.replace("__SEEDED_INIT__", _init_source()))
    write(f"src/{proj}/data.py", head + DATA)
    write(f"src/{proj}/train.py", head + _train_py(ir, proj, config, model_args, backend))
    write("conf/overrides/.gitkeep", "")
    if backend == "hydra":
        write("conf/config.yaml", _yaml(config))
    else:
        write("conf/config.json", json.dumps(config, indent=2, ensure_ascii=False) + "\n")
    write("pyproject.toml", _pyproject(proj, backend))
    write("reproduce.sh", _reproduce(proj, config))
    (out / "reproduce.sh").chmod(0o755)
    # 소스맵은 그래프에서 나온 파일만 센다. env.lock.json은 그래프가 아니라 이 컴퓨터를
    # 기록한 것이라 여기 들어가면 다른 기계의 CI가 "코드가 다르다"고 실패한다.
    write_sourcemap(out, graph=Path(graph_path or source), ir=ir, unit="package",
                    files=list(written), version=version, backend=backend, source=source)
    write("env.lock.json", _env_lock())
    return sorted(written)


def module_name(ir: ModuleGraph) -> str:
    """파이썬 모듈로 쓸 수 있는 프로젝트 이름."""
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "_", ir.graph.name or "model").strip("_").lower()
    cleaned = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", cleaned) or "model"
    return f"m_{cleaned}" if cleaned[0].isdigit() else cleaned


def config_defaults(ir: ModuleGraph) -> dict[str, Any]:
    """Config의 기본값. 순서가 곧 ``--help``에 보이는 순서다."""
    config = dict(BASE_CONFIG)
    train = next((node for node in ir.graph.nodes
                  if (node.type or "").split("@")[0] == "torchflow.Train"), None)
    if train is not None:
        for key in TRAIN_ARGS:
            if key in train.args and not isinstance(train.args[key], dict):
                config[key] = train.args[key]
    data = ((ir.experiment or {}).get("data") or {}) if ir.experiment else {}
    if data.get("name"):
        config["dataset"] = data["name"]
    # 모델 인자는 그래프가 정한다. 값이 없는 런타임 상수(rt.num_classes)는 여기서 채운다.
    for name, spec in codegen.model_params(ir).items():
        default = spec.get("default")
        if default is None:
            default = 10 if name == "num_classes" else 0
        config[name] = default
    return config


def model_arguments(ir: ModuleGraph, config: dict[str, Any]) -> list[str]:
    """``MiniViT(dim=cfg.dim, ..., seed=cfg.seed)``의 인자 목록."""
    names = [name for name in codegen.model_params(ir) if name in config]
    return [f"{name}=cfg.{name}" for name in names] + ["seed=cfg.seed"]


def _header(version: str) -> str:
    return (f"# Generated by TorchFlow {version or '0'}. "
            "This file is part of your project and is your work.\n"
            "# It does not import torchflow: it runs on torch alone.\n")


def _init_source() -> str:
    """``runtime/init.py``를 그대로 가져온다 - model-only가 인라인하는 것과 같은 바이트."""
    source = (Path(__file__).parent / "runtime" / "init.py").read_text(encoding="utf-8")
    body = source.split('"""', 2)[-1]
    for line in ("from __future__ import annotations", "import torch",
                 "from torch import nn", "import hashlib"):
        body = body.replace(line + "\n", "")
    return body.strip()


def _train_py(ir: ModuleGraph, proj: str, config: dict[str, Any],
              model_args: list[str], backend: str) -> str:
    lines = []
    for name, value in config.items():
        lines.append(f"    {name}: {_annotation(value)} = {value!r}")
    body = (TRAIN_HYDRA if backend == "hydra" else TRAIN_ARGPARSE)
    return (body
            .replace("__CLASS__", codegen.class_name(ir))
            .replace("__PROJ__", proj)
            .replace("__CONFIG__", "\n".join(lines))
            .replace("__INPUT_SHAPE__", repr(input_shape(ir)))
            .replace("__MODEL_ARGS__", ", ".join(model_args)))


def input_shape(ir: ModuleGraph) -> list:
    """Input 블록의 출력 규격. 없으면 이미지 한 장 크기를 가정한다."""
    for node in ir.graph.nodes:
        if (node.type or "").split("@")[0] == "torchflow.Input" and node.ports_out:
            return list(node.ports_out[0].shape or [])
    return ["B", 3, 32, 32]


def _annotation(value: Any) -> str:
    return {bool: "bool", int: "int", float: "float", str: "str"}.get(type(value), "str")


def _yaml(config: dict[str, Any]) -> str:
    lines = ["# Generated by TorchFlow. hydra reads this file (§7.3)."]
    for name, value in config.items():
        lines.append(f"{name}: {json.dumps(value, ensure_ascii=False)}")
    return "\n".join(lines) + "\n"


def _pyproject(proj: str, backend: str) -> str:
    extra = '\n  "hydra-core>=1.3",' if backend == "hydra" else ""
    return f"""[project]
name = "{proj.replace('_', '-')}"
version = "0.1.0"
description = "Generated by TorchFlow. Trains without torchflow installed."
requires-python = ">=3.10"
dependencies = [
  "torch>=2.2",
  "numpy>=1.24",{extra}
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
"""


def _reproduce(proj: str, config: dict[str, Any]) -> str:
    """이 파일 하나로 같은 학습이 다시 돈다(§10.2, §17.2)."""
    flags = " ".join(f"--{key} {config[key]!r}".replace("'", "")
                     for key in ("seed", "steps", "batch", "lr") if key in config)
    return f"""#!/usr/bin/env bash
# Generated by TorchFlow. Re-runs the training this graph describes.
set -euo pipefail
cd "$(dirname "$0")"
export PYTHONPATH="src:${{PYTHONPATH:-}}"
# conf/overrides/<run_id>.yaml holds hyper-parameters changed mid-run; pass one with --overrides.
python -m {proj}.train {flags} --deterministic "$@"
"""


def _env_lock() -> str:
    """torch를 import하지 않고 버전만 읽는다 - hub 규칙(§8.1)."""
    from importlib import metadata

    packages = {}
    for name in ("torch", "numpy", "pillow"):
        try:
            packages[name] = metadata.version(name)
        except metadata.PackageNotFoundError:
            continue
    import platform

    return json.dumps({"python": platform.python_version(), "packages": packages},
                      indent=2) + "\n"


def digest(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


SOURCEMAP = ".sourcemap.json"

# 생성 파일에 이 import가 있으면 "torchflow 없이 돈다"가 거짓이 된다(§10.2, §13.1 M6).
IMPORTS_TORCHFLOW = re.compile(r"^\s*(?:import|from)\s+torchflow\b", re.MULTILINE)
# 좌표는 layout.json에만 산다(§10.1). 그래프 파일에 좌표가 새면 편집마다 diff가 시끄러워진다.
HAS_COORDINATES = re.compile(r'"(?:position|pos|x|y)"\s*:\s*-?\d')


def write_sourcemap(root: Path | str, *, graph: Path | str, ir: ModuleGraph, unit: str,
                    files: list[Path], version: str, backend: str = "argparse-dataclass",
                    source: str | None = None, annotated: bool = False) -> Path:
    """무엇을 어떤 그래프에서 어떤 바이트로 썼는지 남긴다(§7.6.2).

    감시기는 여기 적힌 sha와 같은 변경 이벤트를 무시하고(자기 쓰기 억제), CI의
    ``torchflow check``는 이 파일을 기준으로 "코드가 그래프와 같은가"를 묻는다.
    """
    root = Path(root)
    path = root / SOURCEMAP
    graph_path = Path(graph)
    try:
        recorded_graph = graph_path.resolve().relative_to(root.resolve())
    except ValueError:
        recorded_graph = graph_path.resolve()
    payload = {
        "version": version,
        "unit": unit,
        "backend": backend,
        # 그래프를 다시 읽을 자리와, 파일 머리글에 박힌 문자열. 둘은 다를 수 있다.
        "graph": str(recorded_graph),
        "source": source or str(graph),
        # shape 주석은 그래프가 아니라 L0를 한 번 돌린 결과에서 나온다. 그런 파일은
        # 바이트를 다시 만들어 비교할 수 없다 - sha와 무의존 검사만 한다.
        "annotated": annotated,
        "ir_sha256": codegen.ir_hash(ir),
        "files": {str(Path(one).resolve().relative_to(root.resolve())): digest(one)
                  for one in files},
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def check(root: Path | str) -> list[str]:
    """리뷰 계약(§10.2). 빈 목록이면 통과, 아니면 사람이 읽을 문제 목록."""
    import shutil
    import tempfile

    root = Path(root)
    path = root / SOURCEMAP
    if not path.exists():
        return [f"{SOURCEMAP}이 없습니다 - 먼저 torchflow codegen 으로 코드를 뽑으세요"]
    recorded = json.loads(path.read_text(encoding="utf-8"))

    from .ir import load

    graph_path = root / recorded["graph"]
    if not graph_path.exists():
        return [f"그래프 {recorded['graph']} 가 없습니다"]
    ir = load(graph_path)

    problems: list[str] = []
    if codegen.ir_hash(ir) != recorded.get("ir_sha256"):
        problems.append("그래프가 코드 생성 이후에 바뀌었습니다 - codegen을 다시 돌리세요")

    if HAS_COORDINATES.search(graph_path.read_text(encoding="utf-8")):
        problems.append(f"{recorded['graph']} 에 좌표가 들어 있습니다 - 좌표는 layout.json에만 둡니다")

    staging: Path | None = Path(tempfile.mkdtemp(prefix="torchflow-check-"))
    scratch = staging
    try:
        header_source = recorded.get("source") or recorded["graph"]
        if recorded.get("annotated"):
            staging = None
        elif recorded.get("unit") == "package":
            build(ir, staging, version=recorded.get("version", ""), source=header_source,
                  backend=recorded.get("backend", "argparse-dataclass"))
        else:
            target = staging / next(iter(recorded["files"]), "model.py")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(codegen.generate(ir, version=recorded.get("version", ""),
                                               source=header_source), encoding="utf-8")
        for name, sha in recorded["files"].items():
            here = root / name
            fresh = staging / name if staging is not None else None
            if not here.exists():
                problems.append(f"{name} 이 없습니다")
                continue
            if digest(here) != sha:
                problems.append(f"{name} 이 생성 이후에 손으로 고쳐졌습니다")
            elif fresh is not None and fresh.exists() and fresh.read_bytes() != here.read_bytes():
                problems.append(f"{name} 이 지금 그래프에서 나오는 코드와 다릅니다")
            if here.suffix == ".py" and IMPORTS_TORCHFLOW.search(
                    here.read_text(encoding="utf-8")):
                problems.append(f"{name} 이 torchflow를 import합니다 - 생성 코드는 무의존이어야 합니다")
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    return problems


UTILS = '''"""Deterministic init, seeding, schedule and mid-run overrides. torch only."""

from __future__ import annotations

import hashlib
import math
import os
import random
import re
from dataclasses import dataclass
from pathlib import Path

import torch
from torch import nn


__SEEDED_INIT__


def seed_everything(seed: int, deterministic: bool = False) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    try:
        import numpy as np

        np.random.seed(seed)
    except ImportError:
        pass
    if deterministic:
        torch.use_deterministic_algorithms(True, warn_only=True)
        torch.backends.cudnn.benchmark = False
        os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")
        if torch.cuda.is_available():
            torch.backends.cuda.enable_flash_sdp(False)
            torch.backends.cuda.enable_mem_efficient_sdp(False)


def warmup_cosine(optimizer, warmup: int, total: int):
    """One LambdaLR, so that scaling base_lrs stays the only way to change lr."""

    def factor(step: int) -> float:
        if step < warmup:
            return (step + 1) / (warmup + 1)
        progress = (step - warmup) / max(total - warmup, 1)
        return 0.5 * (1 + math.cos(math.pi * min(progress, 1.0)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, factor)


@dataclass
class StepOverride:
    step: int
    path: str
    value: float


class StepOverrides:
    """Replays hyper-parameters changed while a run was training.

    The file is written by TorchFlow as conf/overrides/<run_id>.yaml, one entry per line:
    ``- {step: 120, path: optim.lr, value: 0.0003}``. Only that shape is parsed, so no
    YAML dependency is needed.
    """

    LINE = re.compile(r"step:\\s*(\\d+).*?path:\\s*([\\w.]+).*?value:\\s*([-\\d.eE+]+)")

    def __init__(self, overrides, optimizer, scheduler=None):
        self.pending = sorted(overrides, key=lambda entry: entry.step)
        self.optimizer, self.scheduler = optimizer, scheduler

    @classmethod
    def load(cls, path, optimizer, scheduler=None) -> "StepOverrides":
        entries = []
        if path:
            for line in Path(path).read_text(encoding="utf-8").splitlines():
                found = cls.LINE.search(line)
                if found:
                    entries.append(StepOverride(int(found.group(1)), found.group(2),
                                                float(found.group(3))))
        return cls(entries, optimizer, scheduler)

    def step(self, step: int) -> None:
        while self.pending and self.pending[0].step <= step:
            entry = self.pending.pop(0)
            key = entry.path.split(".", 1)[-1]
            if key == "lr" and self.scheduler is not None:
                # Writing param_groups["lr"] would be undone by the next scheduler step,
                # so scale the base instead - the same rule the TorchFlow worker follows.
                base = self.scheduler.base_lrs[0]
                scale = entry.value / base if base else 1.0
                self.scheduler.base_lrs = [b * scale for b in self.scheduler.base_lrs]
                for group in self.optimizer.param_groups:
                    group["initial_lr"] = group.get("initial_lr", group["lr"]) * scale
                    group["lr"] = group["lr"] * scale
            else:
                for group in self.optimizer.param_groups:
                    group[key] = entry.value
'''


DATA = '''"""Batches for training. torch + numpy only, no torchflow.

Two sources, chosen by ``cfg.dataset``:

* ``teacher`` / ``noise`` - a synthetic task built from the seed alone. ``teacher``
  labels are the argmax of a fixed random projection, so the loss actually goes down
  and "does the loop work" is answerable without any download.
* anything else - ``<data_root>/<dataset>/`` on disk, in one of the three layouts
  TorchFlow reads: ``x.npy`` + ``y.npy``, one folder per class holding images, or a
  single csv whose last column is the label. Split 80/20 with seed 0, same as the app.
"""

from __future__ import annotations

from pathlib import Path

import torch

IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".bmp", ".webp")


def build_loaders(cfg, device, input_shape):
    """Returns ``(endless batch iterator, evaluate or None)``."""
    generator = torch.Generator().manual_seed(cfg.seed)
    if cfg.dataset in ("teacher", "noise"):
        shape = [int(dim) for dim in input_shape[1:]]
        return synthetic(shape, cfg.num_classes if hasattr(cfg, "num_classes") else 10,
                         cfg.batch, device, generator, learnable=cfg.dataset != "noise"), None
    splits = load_folder(Path(cfg.data_root) / cfg.dataset)
    return (epochs(splits["train"], cfg.batch, device, generator),
            evaluator(splits["test"], device))


def synthetic(shape, classes, batch, device, generator, *, learnable=True):
    features = 1
    for dim in shape:
        features *= int(dim)
    teacher = torch.randn(features, classes, generator=generator) if learnable else None
    while True:
        inputs = torch.randn([batch, *shape], generator=generator)
        if teacher is None:
            targets = torch.randint(0, classes, (batch,), generator=generator)
        else:
            targets = (inputs.flatten(1) @ teacher).argmax(dim=1)
        yield inputs.to(device), targets.to(device)


def epochs(split, batch, device, generator):
    inputs, targets = split
    while True:
        order = torch.randperm(len(inputs), generator=generator)
        for start in range(0, len(order) - batch + 1, batch):
            index = order[start:start + batch]
            yield inputs[index].to(device), targets[index].to(device)


def evaluator(split, device, batch: int = 1000):
    inputs, targets = split

    def evaluate(model, loss_fn) -> dict:
        total_loss = correct = 0.0
        with torch.no_grad():
            for start in range(0, len(inputs), batch):
                x = inputs[start:start + batch].to(device)
                y = targets[start:start + batch].to(device)
                output = model(x)
                total_loss += float(loss_fn(output, y)) * len(y)
                correct += float((output.argmax(dim=1) == y).sum())
        return {"val_loss": total_loss / len(inputs), "val_acc": correct / len(inputs)}

    return evaluate


def load_folder(folder: Path) -> dict:
    """Reads one of the three layouts and splits it 80/20 with seed 0."""
    import numpy as np

    if not folder.is_dir():
        raise SystemExit(
            f"no data at {folder}. Put it there (x.npy + y.npy, one folder per class, "
            f"or a csv), point --data_root elsewhere, or run with --dataset teacher.")
    if (folder / "x.npy").exists():
        x = np.load(folder / "x.npy")
        y = np.load(folder / "y.npy")
    elif any(folder.glob("*.csv")):
        table = np.genfromtxt(next(iter(sorted(folder.glob("*.csv")))), delimiter=",",
                              skip_header=1, dtype=float)
        table = table[~np.isnan(table).any(axis=1)]
        x, y = table[:, :-1], table[:, -1]
    else:
        x, y = _images(folder, np)

    inputs = torch.as_tensor(np.asarray(x), dtype=torch.float32)
    targets = torch.as_tensor(np.asarray(y), dtype=torch.long)
    if inputs.max() > 1.5:                       # 0..255 images -> 0..1
        inputs = inputs / 255.0
    order = torch.randperm(len(inputs), generator=torch.Generator().manual_seed(0))
    cut = int(len(order) * 0.8)
    return {"train": (inputs[order[:cut]], targets[order[:cut]]),
            "test": (inputs[order[cut:]], targets[order[cut:]])}


def _images(folder: Path, np):
    from PIL import Image

    classes = sorted(child.name for child in folder.iterdir() if child.is_dir())
    if not classes:
        raise FileNotFoundError(f"no data found in {folder}")
    arrays, labels = [], []
    for index, name in enumerate(classes):
        for path in sorted((folder / name).iterdir()):
            if path.suffix.lower() not in IMAGE_SUFFIXES:
                continue
            picture = np.asarray(Image.open(path).convert("RGB"), dtype="float32")
            arrays.append(picture.transpose(2, 0, 1))
            labels.append(index)
    return np.stack(arrays), np.asarray(labels)
'''


TRAIN_ARGPARSE = '''"""Training entry point. ``python -m __PROJ__.train --steps 500``.

Everything the graph knew is a Config field, so ``--help`` is the full list.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import asdict, dataclass, fields
from pathlib import Path

import torch
from torch import nn

from .data import build_loaders
from .model import __CLASS__
from .utils import StepOverrides, seed_everything, warmup_cosine


@dataclass
class Config:
__CONFIG__


# The Input block's port spec. The synthetic task draws batches in this shape.
INPUT_SHAPE = __INPUT_SHAPE__


def parse() -> Config:
    parser = argparse.ArgumentParser(prog="python -m __PROJ__.train")
    for field in fields(Config):
        if isinstance(field.default, bool):
            parser.add_argument(f"--{field.name}", action=argparse.BooleanOptionalAction,
                                default=field.default)
        else:
            parser.add_argument(f"--{field.name}", type=type(field.default),
                                default=field.default)
    return Config(**vars(parser.parse_args()))


def pick_device(requested: str):
    if requested and requested != "auto":
        return torch.device(requested)
    if torch.cuda.is_available():
        return torch.device("cuda", torch.cuda.current_device())
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def make_optimizer(model, cfg: Config):
    if cfg.optimizer == "sgd":
        return torch.optim.SGD(model.parameters(), lr=cfg.lr, momentum=0.9,
                               weight_decay=cfg.weight_decay)
    if cfg.optimizer == "adam":
        return torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    return torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)


def save(path: Path, model, optimizer, scheduler, step: int) -> None:
    """Write to a temporary file and swap it in - a half-written checkpoint is unreadable."""
    payload = {"model": model.state_dict(), "optimizer": optimizer.state_dict(),
               "scheduler": scheduler.state_dict() if scheduler is not None else None,
               "step": step}
    temporary = path.with_suffix(".tmp")
    torch.save(payload, temporary)
    temporary.replace(path)


def main() -> None:
    cfg = parse()
    seed_everything(cfg.seed, deterministic=cfg.deterministic)
    device = pick_device(cfg.device)
    run_dir = Path(cfg.run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "config.json").write_text(json.dumps(asdict(cfg), indent=2), encoding="utf-8")

    torch.manual_seed(cfg.seed)
    model = __CLASS__(__MODEL_ARGS__).to(device)
    model.train()
    batches, evaluate = build_loaders(cfg, device, INPUT_SHAPE)
    optimizer = make_optimizer(model, cfg)
    scheduler = (warmup_cosine(optimizer, cfg.warmup_steps, cfg.steps)
                 if cfg.scheduler == "cosine" else None)
    overrides = StepOverrides.load(cfg.overrides, optimizer, scheduler)
    loss_fn = nn.CrossEntropyLoss()

    step = 0
    if cfg.resume:
        state = torch.load(cfg.resume, map_location="cpu")
        model.load_state_dict(state["model"])
        optimizer.load_state_dict(state["optimizer"])
        if scheduler is not None and state.get("scheduler"):
            scheduler.load_state_dict(state["scheduler"])
        step = int(state.get("step", 0))

    started = time.time()
    with (run_dir / "metrics.jsonl").open("a", encoding="utf-8") as log:
        def record(**fields) -> None:
            log.write(json.dumps(fields) + "\\n")
            log.flush()

        while step < cfg.steps:
            inputs, targets = next(batches)
            loss = loss_fn(model(inputs), targets)
            if not torch.isfinite(loss):
                save(run_dir / "nan.pt", model, optimizer, scheduler, step)
                raise SystemExit(f"loss is not finite at step {step}")
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            if cfg.grad_clip > 0:
                nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
            optimizer.step()
            if scheduler is not None:
                scheduler.step()
            step += 1
            overrides.step(step)
            if step % cfg.log_every == 0 or step == cfg.steps:
                lr = float(optimizer.param_groups[0]["lr"])
                record(step=step, loss=float(loss.item()), lr=lr)
                print(f"step {step:>6} / {cfg.steps}   loss {float(loss.item()):.4f}   lr {lr:.3g}",
                      flush=True)
            if evaluate is not None and (step % cfg.eval_every == 0 or step == cfg.steps):
                model.eval()
                metrics = evaluate(model, loss_fn)
                model.train()
                record(step=step, **metrics)
                print(f"step {step:>6} / {cfg.steps}   "
                      + "   ".join(f"{k} {v:.4f}" for k, v in metrics.items()), flush=True)
            if step % cfg.eval_every == 0 or step == cfg.steps:
                save(run_dir / "last.pt", model, optimizer, scheduler, step)
    print(f"done - {step} steps in {time.time() - started:.1f}s", flush=True)


if __name__ == "__main__":
    main()
'''

# hydra 백엔드는 진입점만 다르다. 학습 루프는 같은 것을 쓴다.
TRAIN_HYDRA = TRAIN_ARGPARSE.replace(
    '''def parse() -> Config:
    parser = argparse.ArgumentParser(prog="python -m __PROJ__.train")
    for field in fields(Config):
        if isinstance(field.default, bool):
            parser.add_argument(f"--{field.name}", action=argparse.BooleanOptionalAction,
                                default=field.default)
        else:
            parser.add_argument(f"--{field.name}", type=type(field.default),
                                default=field.default)
    return Config(**vars(parser.parse_args()))''',
    '''def parse() -> Config:
    """hydra backend: conf/config.yaml wins, and CLI overrides win over that.

    ``python -m __PROJ__.train steps=100 lr=3e-4``
    """
    import sys

    from omegaconf import OmegaConf

    root = Path(__file__).resolve().parents[2]
    merged = OmegaConf.merge(OmegaConf.structured(Config()),
                             OmegaConf.load(root / "conf" / "config.yaml"),
                             OmegaConf.from_dotlist([a for a in sys.argv[1:] if "=" in a]))
    return Config(**OmegaConf.to_container(merged))''')
